output_dir: /HDD/_projects/benchmark/semantic_segmentation/new_model/outputs/torch
# data_path: /HDD/_projects/benchmark/semantic_segmentation/new_model/datasets/tenneco/split_patch_mask_dataset

epochs: 150
lr_warmup_epochs: 0
lr_warmup_method: linear
lr_warmup_decay: 0.01
print_freq: 10
# ckpt: /HDD/_projects/benchmark/semantic_segmentation/new_model/outputs/torch/dlv3_scratch_tear_stabbed_deeplabv3_resnet50_20_22_21/model_99.pth
# resume: True
ckpt: null
resume: False
start_epoch: 0


amp: False

optimizer:
  type: SGD
  case_sensitive: true
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0001
  

loss:
  type: LossWithAux
  case_sensitive: true
  loss_name: CrossEntropyLoss # loss_name?
  label_smoothing: 0.0

loop:
  type: EpochBasedLoop
  case_sensitive: true

dataset: 
  type: MaskDatasetWrapper
  case_sensitive: true
  load_dataset: 
    type: MaskDataset
    case_sensitive: true
  classes:
    - SCRATCH
    - TEAR
    - STABBED


dataloader:
  type: torch_dataloader
  case_sensitive: false

  train:
    batch_size: 32
    workers: 16

  val:
    batch_size: 4
    workers: 16

model: 
  type: TorchvisionModel
  case_sensitive: true
  model_name: deeplabv3_resnet50
  aux_loss: True
  weights: null
  weights_backbone: ResNet50_Weights.IMAGENET1K_V1


augment: 
  train:
    backend: PIL
    use_v2: False
  val:
    backend: PIL
    use_v2: False
  

monitor:
  use: true

train:
  device_ids: 0
  device: cuda
  use_deterministic_algorithms: False

  sync_bn: true

distributed:
  world_size: 1
  dist_url: env://

archive:
  output_dir: /HDD/_projects/benchmark/semantic_segmentation/new_model/outputs/torch

  model:
    save_last: true 
    save_best: 
      loss: true 
      acc: true
    save_freq_epoch: 10

  monitor:
    use: true
    save_freq_epoch: 10

  val:
    save_freq_epoch: 10

