output_dir: /HDD/_projects/benchmark/classification/rps/outputs
input_dir: /HDD/_projects/benchmark/classification/rps/datasets/split_dataset

dataset: 'cifar10'

type: "resnet18"
device_ids: 0
batch_size: 8
epochs: 90

amp: True
