model:
  type: "resnet"

dataset:
  type: DirectoryDataset
  input_dir: /HDD/_projects/benchmark/classification/rps/datasets/split_dataset

output_dir: /HDD/_projects/benchmark/classification/rps/outputs

device_ids: 0
batch_size: 8
epochs: 90

amp: True
