model:
  type: "resnet"

dataset:
  type: DirectoryDataset
  input_dir: /HDD/_projects/benchmark/classification/rps/datasets/split_dataset

archive: 
  output_dir: /HDD/_projects/benchmark/classification/rps/outputs

train:
  device_ids: 0,1
  batch_size: 8
  epochs: 90

  amp: True
