_BASE_: ../Base-SBS.yml

MODEL:
  BACKBONE:
    NAME: build_resnest_backbone

DATASETS:
  NAMES: ("MOT17",)
  TESTS: ("MOT17",)

OUTPUT_DIR: /HDD/etc/outputs/tracking/tracktrack/2. fastreid/logs/MOT17/sbs_S50