
model:
  backend: 'torchvision'
  model_name: 'resnet'
  backbone: '18'
  weights: null
  num_classes: null

ema: 
  use: False
  steps: 32
  decay: 0.99998

loss:
  loss_name: CrossEntropyLoss
  label_smoothing: 0.0

optimizer:
  optimizer_name: SGD
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0001
  
  norm_weight_decay: null
  bias_weight_decay: null
  transformer_embedding_decay: null

scheduler:
  scheduler_name: StepLR
  step_size: 30
  gamma: 0.1
  eta_min: 0.0

warmup_scheduler:
  warmup_scheduler_name: ConstantLR
  total_iters: 0
  factor: 0.01
  integrate_scheduler_name: SequentialLR


ckpt: null
device: "cuda"
device_ids: '0,1'
batch_size: 8
epochs: 90
workers: 16

resume: ""
cache_dataset: False
sync_bn: True
test_only: False

# Mixed precision training parameters
amp: True

# distributed training parameters
world_size: 1
dist_url: "env://"

print_freq: 10

use_deterministic_algorithms: False
clip_grad_norm: 1.0
ra_sampler: True
ra_reps: 4

topk: 3

# augment:
mixup_alpha: 0.0
cutmix_alpha: 0.0

# val_resize_size: 256
# val_crop_size: 224
# train_crop_size: 224
# interpolation: "bilinear"

# auto_augment: null
# ra_magnitude: 9
# augmix_severity: 3
# random_erase: 0.0

use_v2: False # Use V2 transforms
# backend: PIL