
model:
  backend: 'torchvision_model'
  model_name: 'resnet'
  backbone: '18'
  weights: null
  num_classes: null

ema: 
  use: False
  steps: 32
  decay: 0.99998

loss:
  loss_name: cross_entropy
  label_smoothing: 0.0

optimizer:
  optimizer_name: sgd
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0001
  
scheduler:
  scheduler_name: steplr
  lr_warmup_epochs: 0
  lr_warmup_method: "constant"
  lr_warmup_decay: 0.01
  lr_step_size: 30
  lr_gamma: 0.1
  lr_min: 0.0

ckpt: null
device: "cuda"
device_ids: '0,1'
batch_size: 8
epochs: 90
workers: 16

norm_weight_decay: null
bias_weight_decay: null
transformer_embedding_decay: null
label_smoothing: 0.0
mixup_alpha: 0.0
cutmix_alpha: 0.0


resume: ""
cache_dataset: False
sync_bn: True
test_only: False
auto_augment: null

ra_magnitude: 9
augmix_severity: 3
random_erase: 0.0

# Mixed precision training parameters
amp: True

# distributed training parameters
world_size: 1
dist_url: "env://"

print_freq: 10



use_deterministic_algorithms: False
interpolation: "bilinear"
val_resize_size: 256
val_crop_size: 224
train_crop_size: 224
clip_grad_norm: 1.0
ra_sampler: True
ra_reps: 4
backend: PIL
use_v2: False # Use V2 transforms

topk: 3