
model:
  backend: 'torchvision'
  type: 'resnet'
  backbone: '18'
  weights: null
  ema: 
    use: False
    steps: 32
    decay: 0.99998

loss:
  type: CrossEntropyLoss
  label_smoothing: 0.0

optimizer:
  type: SGD
  lr: 0.1
  momentum: 0.9
  weight_decay: 0.0001
  
  norm_weight_decay: null
  bias_weight_decay: null
  transformer_embedding_decay: null

scheduler:
  type: StepLR
  step_size: 30
  gamma: 0.1
  eta_min: 0.0

warmup_scheduler:
  warmup_type: ConstantLR
  total_iters: 0
  factor: 0.01
  integrate_type: SequentialLR

dataset:
  type: DirectoryDataset 
  load_method: image_folder
  sampler: 
    type: RASampler
    reps: 4

loop:
  type: EpochBasedLoop

resume: 
  use: False

train:
  trainer:
    type: base_trainer
  ckpt: null
  device: "cuda"
  device_ids: '0,1'
  batch_size: 8
  epochs: 90
  workers: 16

  cache_dataset: False
  sync_bn: True
  test_only: False

  amp: True
  use_deterministic_algorithms: False
  clip_grad_norm: 1.0

  print_freq: 10
  topk: 3

val:
  validator:
    type: base_validator
  epoch: 2
  batch_size: 2
  workers: 16


distributed:
  world_size: 1
  dist_url: "env://"

augment:
  mixup_cutmix: 
    mixup_alpha: 0.0
    cutmix_alpha: 0.0
    use_v2: False # Use V2 transforms

  # val_resize_size: 256
  # val_crop_size: 224
  # train_crop_size: 224
  # interpolation: "bilinear"

  # auto_augment: null
  # ra_magnitude: 9
  # augmix_severity: 3
  # random_erase: 0.0

  # backend: PIL

archive:
  save_model:
    last: True 
    best: 
      loss: True 
      acc: True
    freq_epoch: 10

  monitor:
    use: True

  save_val:
    use: True
