
save_folder: /HDD/etc/semdedup/outputs/results
sorted_clusters_path: /HDD/etc/semdedup/outputs/sorted_clusters
# -- number of clusters
num_clusters: 300 #50000
embs_memory_loc: 
# -- dataset size
dataset_size: 3835
# -- embeddings size
emd_size: 768
# -- which example to keep from each group of duplicates
which_to_keep: "hard"
# -- seed
seed: 1234
# -- largest cluster size the memory is large enough to process. If the cluster size is larger than it, we will devide the cluster into small clusters and process each one separately.
largest_cluster_size_to_process: 100000

